"""CI PR reviewer — calls Anthropic API and emits GITHUB_OUTPUT review_body."""
from __future__ import annotations

import os
import sys
import textwrap

import anthropic

PROMPT_TEMPLATE = textwrap.dedent("""\
    You are a senior software engineer reviewing a pull request.
    Respond ONLY in Traditional Chinese (程式碼/指令保持英文).

    PR Title: {pr_title}
    PR Description:
    {pr_body}

    Diff (truncated to 28 000 chars):
    ```diff
    {diff}
    ```

    Write exactly four sections using these Markdown headings:

    ## 🗺 Planner
    [What problem this PR solves and whether the overall approach is sound]

    ## ⚙️ Executor
    [What was actually changed — key files, logic, data-model impact]

    ## 🔍 Reviewer
    [Concrete issues found: bugs, security risks, missing error handling, style nits.
     If none, say so explicitly.]

    ## 🧪 Testing
    [Test coverage assessment: what is tested, what is missing, whether edge cases are covered]

    Be specific and concise. Each section ≤ 10 bullet points.
""")


def main() -> None:
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        print("ANTHROPIC_API_KEY not set — skipping review", file=sys.stderr)
        _write_output("⚠️ `ANTHROPIC_API_KEY` secret not configured — AI review skipped.")
        return

    pr_title = os.environ.get("PR_TITLE", "(no title)")
    pr_body = os.environ.get("PR_BODY", "(no description)")
    diff = os.environ.get("DIFF", "")

    if not diff.strip():
        _write_output("ℹ️ No reviewable diff found.")
        return

    prompt = PROMPT_TEMPLATE.format(
        pr_title=pr_title,
        pr_body=pr_body or "(no description)",
        diff=diff,
    )

    client = anthropic.Anthropic(api_key=api_key)
    message = client.messages.create(
        model="claude-opus-4-7",
        max_tokens=2048,
        messages=[{"role": "user", "content": prompt}],
    )
    review_text = message.content[0].text

    output = f"<!-- ai-review -->\n{review_text}\n\n---\n🤖 Generated by [PR Auto-Review](../.github/workflows/pr-review.yml)"
    _write_output(output)


def _write_output(body: str) -> None:
    github_output = os.environ.get("GITHUB_OUTPUT", "")
    if github_output:
        delimiter = "EOF_REVIEW"
        with open(github_output, "a") as f:
            f.write(f"review_body<<{delimiter}\n{body}\n{delimiter}\n")
    else:
        print(body)


if __name__ == "__main__":
    main()
